### ISSUE TITLE
hello, Andi

### ISSUE THREAD

**Issue by GlistenSTAR** [andidp/customer_db_api#6]
hello, Andi
I am danil
what is your skype id? we can continue work in the future.
I have many project.

**Comment by andidp** [comment]
Hi Daniil,
Is skype still used now? hehe

skype: *andidp*

But, I just have time in the night, maybe for 3-4 hours bro.

Thanks

Kind Regards,

Andi Dwi Purnama ST
*Software Engineer*
p/wa: + <+6285729451113>628812744669
e: ***@***.***
w: andigowrite.wordpress.com



Pada tanggal Min, 14 Mar 2021 pukul 03.28 GlistenSTAR <
***@***.***> menulis:

**Comment by GlistenSTAR** [comment]
Hello, Andi
my skype id is live:.cid.b63fecafe0a27ff8
Call me, I send the data through there.

**Comment by GlistenSTAR** [comment]
Can you see it?

**Comment by GlistenSTAR** [comment]
Check the issues

**Comment by GlistenSTAR** [comment]
hello, are you there? 
We communicate through skype

**Comment by GlistenSTAR** [comment]
What is your skype id? send it through here.
