### ISSUE TITLE
Read this(urgent)

### ISSUE THREAD

**Issue by GlistenSTAR** [andidp/customer_db_api#7]
#Hello, Andi
Please see the skype now.
I am very urgent.
If you finish this, I will release the money soon.
If you see my message, Please contact me.......

From you friend

**Comment by GlistenSTAR** [comment]
#6 Can you read this now?

**Comment by GlistenSTAR** [comment]
@andidp **Please send me the response**

**Comment by GlistenSTAR** [comment]
💯 :(

**Comment by GlistenSTAR** [comment]
Hello, Andi
When you show this message, please contact me...
that is urgent problem....
Quickly.....

**Comment by GlistenSTAR** [comment]
Hello, bro
It's very difficult to communicate.
I want to meet you again.
From your dear friend.

**Comment by andidp** [comment]
Hello Bro, Please create issue here if the issue is related to my work in Memestock. If new task in New project, I will contact you at 16.00 my time (Jakarta time). Sorry I am busy brother

**Comment by GlistenSTAR** [comment]
hello, andi
Time is up

**Comment by GlistenSTAR** [comment]
hello, andi
please send response

**Comment by GlistenSTAR** [comment]
Now remain one problem.
when you click on the number under “Tweeted” it takes you back to Reddit instead of Twitter search for that keyword stock 
Do you understand my mean?
https://api.asm.skype.com/v1/objects/0-eus-d14-89f3c1404c07229bc108d2985c8c0152/views/imgpsh_mobile_save_anim
Please carefully see X sign.
I wanna like this.
https://api.asm.skype.com/v1/objects/0-eus-d11-8bdc75d24eec92039f8671f5352bd220/views/imgpsh_mobile_save_anim

If you see my message, please contact me......

**Comment by GlistenSTAR** [comment]
when do you free?

**Comment by GlistenSTAR** [comment]
hello, bro.
Are you there?

**Comment by GlistenSTAR** [comment]
hello

**Comment by GlistenSTAR** [comment]
When do you free?
It's very difficult communicate you...
:(
:(
:(

**Comment by GlistenSTAR** [comment]
when do you reply?

**Comment by GlistenSTAR** [comment]
when I click the twiiter number, It's go to reddit page. can you fix this? It's my last aim.
Do you understand my mean?

**Comment by andidp** [comment]
Ok I will fix it today Bro, sorry for my late reply. I am very busy, I did't slept last night to creating some endpoint

**Comment by GlistenSTAR** [comment]
hello, bro. Please fix this problem asap. I want you fix this problem on today. thanks Andi.

**Comment by GlistenSTAR** [comment]
Hello, andi
Are you free now?

**Comment by GlistenSTAR** [comment]
Hello, bro
How does it going?
I am wait your reponse now....

**Comment by GlistenSTAR** [comment]
we must finish this project on today.
So please reply asap.

**Comment by GlistenSTAR** [comment]
When do you reply?
When you fix this, I will give the project with CakePHP project.
Do you know about CakePHP?

**Comment by GlistenSTAR** [comment]
:( 💯

**Comment by GlistenSTAR** [comment]
Hey, when do you reply?

**Comment by andidp** [comment]
Hi @GlistenSTAR I already fixed the javascript directly in the live site. Please check.
Thanks

**Comment by GlistenSTAR** [comment]
Thanks, andi
You are best my friend.
when I have another project, I will contact you. 
Anyway do you know about symfony?

**Comment by GlistenSTAR** [comment]
You are perfect.

**Comment by andidp** [comment]
Ok my friend. Symfony is like Laminas haha. And I have experiences in Laminas.

**Comment by GlistenSTAR** [comment]
good, I have symfony project. It need the add the backend.
but when do you free? I mean free time?
I know you are very busy.

**Comment by GlistenSTAR** [comment]
hahaha, when do you free?

**Comment by GlistenSTAR** [comment]
what is your job?

**Comment by andidp** [comment]
Huaha I'm free after work hour. t let's try with first task bro and see, I can do this or not after my work hour hihi

**Comment by GlistenSTAR** [comment]
good
[MercadoFree - integracion PagoFree (1).pdf](https://github.com/andidp/customer_db_api/files/6175990/MercadoFree.-.integracion.PagoFree.1.pdf)

First read this. It's language is spanish. On frontend you may add the one tab and you add the backend rest.

**Comment by GlistenSTAR** [comment]
My main aim is make like this.
https://xd.adobe.com/view/e36ba4f6-9e04-4b4a-a4d8-b6829591aa9f-b638/

Now I make the frontend, I will intergration mobile app and web site.
Do you understand my means?

**Comment by GlistenSTAR** [comment]
[hdjhakjg_mercadofree_test.zip](https://github.com/andidp/customer_db_api/files/6176012/hdjhakjg_mercadofree_test.zip)
it's db

**Comment by GlistenSTAR** [comment]
[payum-bundle.zip](https://github.com/andidp/customer_db_api/files/6176088/payum-bundle.zip)

extract here : vender/payum/

**Comment by andidp** [comment]
haha

**Comment by GlistenSTAR** [comment]
Do you run the project as well?

**Comment by GlistenSTAR** [comment]
Hello, bro
Are you there?

**Comment by andidp** [comment]
Halo Bro, sorry, still work hour here Bro. Maybe 4 hours fron now. I will contact you

**Comment by andidp** [comment]
Just create the task in Asana or whatever, so I will do the tasks when I am finish my work.

**Comment by GlistenSTAR** [comment]
Hello, Andi
How are you?
Do you have experience in SEO?
If you have experience, please let me know. I will raise up the ranking memestock.com
If you see my message, please ping me.

**Comment by GlistenSTAR** [comment]
hello

**Comment by GlistenSTAR** [comment]
hello, andi.
how are you? I wanna upgrade the memestock. I wanna add the new one tab.
If you see my meeage, please contact me.

**Comment by GlistenSTAR** [comment]
hello, andi
we can communicate with skype

**Comment by GlistenSTAR** [comment]
???

**Comment by GlistenSTAR** [comment]
hello, andi
If you see my message, please contact me...
I wanna discuss important problem

**Comment by GlistenSTAR** [comment]
Hello, Andi. How are you? I call you because I have a personal problem.
My Upwork account is breaked. So I can't work on my upwork account. Upwork is my life line. but :( :( :( 
I know you are very busy because of your job.
Can you borrow your Upwork account? I had experience with Upwork. So I know that route. So I can earn over 5K~8K USD, when I earn the money I will pay 10% money to you . What Do you think? I wish we could cooperate with each other. 
If you see my message, please contact me on skype or here.
I will wait for your kindly response.
From Danil.

**Comment by GlistenSTAR** [comment]
Hello, Andi
Don't worry, I can grow up your account, Please borrow it, During make the project, I know about you and you are very honest and very trustable. we should help each other. I will alway honest you and I will give 10% of profit. If you have a time, you can check your account anytime. 
Please Please borrow your upwork account.
I wish work with you forever ever.
Did you finish one project on Upwork?
I will wait your kindly response.
If you want, I can tell all about me.
If you see my message, Please contact me.

**Comment by GlistenSTAR** [comment]
Hello, Andi
Now I am waiting your kindly response
Please ping me.
